### ISSUE TITLE
XSS Security Vulnerability

### ISSUE THREAD

**Issue by lee-jongwoo** [msk-apps/msk-markdown#23]
Try entering this markdown syntax:
```
[Click Me](javascript:alert('XSS'))
```
This can allow malicious scripts to run on **any** user's browser that views this.

These problems are also mentioned in marked.js too:
> Warning: 🚨 Marked does not sanitize the output HTML. Please use a sanitize library, like DOMPurify (recommended), sanitize-html or insane on the output HTML! 🚨

I'm no security expert, but I'm pretty sure:
We'll need to _sanitize_ the inputs.

**IMPORTANT**: We need to sanitize the markdown **after** marked.js processes it, because of attacks like this:
```
> hello <a name="n"
> href="javascript:alert('XSS')">*you*</a>
```

**Comment by kevinmmansour** [comment]
OK. We can use [DOMPurify](https://github.com/cure53/DOMPurify). I would appreciate if you can create a pull request (if applicable).
