### ISSUE TITLE
marked is not a function

### ISSUE THREAD

**Issue by CFarhad** [msk-apps/msk-markdown#29]
**Describe the bug**
we have a amazing error and it is `marked is not a function`;
with this error website can not compile my markdown and it freezes.
i type many word but it compiles 2 letter.

**Screenshots**
![image](https://user-images.githubusercontent.com/44419462/144723508-3bca29bd-fa92-4735-9043-934bf012816b.png)

**Comment by lee-jongwoo** [comment]
Oops, typo found in main.js
Should be `marked.parse()`, not `marked()`

I’ll fix that as soon as i get home
