### ISSUE TITLE
when click on download button without name file is saving

### ISSUE THREAD

**Issue by bharat-dussa** [msk-apps/msk-markdown#34]
**Describe the bug**
When we click on the download button without giving name to the file it is saving which should not happen right.

**Desktop (If applicable, please complete the following information):**
 - OS: [linux]
 - Browser [Google Chrome]
 - Version [ 97.0.4692.99 ]

**Comment by VijayKumarKTG** [comment]
I would love to work on this issue @bharat-dussa

**Comment by Mahmoudgalalz** [comment]
Hello, I got ur point. there's a bug that happens when u click to download it's downloading a txt file not .md file
so I will handle it and make a pull request

**Comment by Mahmoudgalalz** [comment]
@KhantParthkumarA can I make this pull request

**Comment by Mahmoudgalalz** [comment]
@KhantParthkumarA I'm done with this issue, I did a pull request
thanks for contributing

**Comment by Mahmoudgalalz** [comment]
can we close this issue

**Comment by kevinmmansour** [comment]
Sure
