### ISSUE TITLE
Save on local storage

### ISSUE THREAD

**Issue by Mahmoudgalalz** [msk-apps/msk-markdown#35]
if we are working on documentation or something like that, 
I think it would be a disaster if the browser is closed.

So I would like to save the text on our local storage

**Comment by Mahmoudgalalz** [comment]
@kevinmmansour 
can I do this?

**Comment by kevinmmansour** [comment]
@Mahmoudgalalz Yes, sure.

**Comment by Mahmoudgalalz** [comment]
@kevinmmansour okay I'm done with this feature, I will do a pull request now. and I'm working on the **bug** for downloading

**Comment by Mahmoudgalalz** [comment]
I don't have push access so how can I do that?
@kevinmmansour 
@KhantParthkumarA

**Comment by kevinmmansour** [comment]
@Mahmoudgalalz Pull request? and I will review and accept.

**Comment by Mahmoudgalalz** [comment]
@kevinmmansour 
I opened the pull request but how could I push my code ?

**Comment by Mahmoudgalalz** [comment]
done @kevinmmansour

**Comment by kevinmmansour** [comment]
Thanks

**Comment by Mahmoudgalalz** [comment]
ur welcome it's a useful app, and I use it to write my documentation
