### ISSUE TITLE
Include the .md extension on CONTRIBUTING and LICENSE

### ISSUE THREAD

**Issue by chase-mortensen** [msk-apps/msk-markdown#40]
**What is the improvement?**
Github formats markdown files nicely, but it doesn't recognize these files as being markdown since they are missing the extension.
**Additional context**
I think this small fix would improve the readability of these files. I plan on making a PR. 

Side note: This is my first issue/PR, so any suggestions are welcome. Thanks

**Comment by kevinmmansour** [comment]
Oh thanks for making PR.
