### ISSUE TITLE
When tab key is pressed, editor does not indent

### ISSUE THREAD

**Issue by pratik-pdw** [msk-apps/msk-markdown#43]
Can we have this feature, wherein if user presses tab key the editor should indent content. 
I feel this is useful when writing code in markdown.

**Comment by Mahmoudgalalz** [comment]
@kevinmmansour can you assignee this issue to me ?
@pratik-pdw I will work on it

**Comment by Mahmoudgalalz** [comment]
Done, I made a PR

**Comment by LaideLawal** [comment]
Hello, I can see this issue is lingering on since April, can I give it a shot?

**Comment by Mahmoudgalalz** [comment]
I finished it but the pr is not merged yet

**Comment by kevinmmansour** [comment]
It's all done now, I can close this.
