### ISSUE TITLE
Pluralisation issue with the char and word count

### ISSUE THREAD

**Issue by double-beep** [msk-apps/msk-markdown#9]
A picture is worth a thousand words :)

![image](https://user-images.githubusercontent.com/38133098/122814242-963ab500-d2dc-11eb-8123-73e37330033a.png)

**Comment by kevinmmansour** [comment]
What is browser version? Also which preview version you are using?

**Comment by double-beep** [comment]
Is this information even relevant?

**Comment by kevinmmansour** [comment]
Yes, Browser Info. I am using Firefox 89 and I didn't meet same issue. Also which Link you viewed the project on.

**Comment by double-beep** [comment]
[This](https://msk-markdown.netlify.app/) one. Chrome 91.0.4472.114. It should be "1 Char" and "1 Word" respectively.

**Comment by kevinmmansour** [comment]
Looks like a font issue. I have tested on Chrome 91.0.4472.114 (Same like yours) and also I didn't meat same issue. So Is there any errors in the console or block the fonts. I am using Google Fonts. Thank you for reporting.

**Comment by kevinmmansour** [comment]
For Reference, This is the Screenshot for Google Chrome:

![Screenshot](https://user-images.githubusercontent.com/71846550/122836301-46ff7f00-d2f2-11eb-93b5-24e60e221e42.png)

**Comment by double-beep** [comment]
Have you tried typing some characters?

**Comment by Oaphi** [comment]
@kevinmmansour it's [line 74](https://github.com/msk-apps/msk-markdown/blob/master/main.js#L74) that is faulty - you do not do any pluralization logic there. You need to wrap the pluralizable strings into a utility function (inability to do so bugs SE to this day, btw)

**Comment by kevinmmansour** [comment]
> 
> 
> Have you tried typing some characters?

Yes.

**Comment by kevinmmansour** [comment]
> 
> 
> @kevinmmansour it's [line 74](https://github.com/msk-apps/msk-markdown/blob/master/main.js#L74) that is faulty (and line 73 for that matter) - you do not do any pluralization logic there. You need to wrap the pluralizable strings into a utility function (inability to do so bugs SE to this day, btw).
> 
> A semi-naive implementation would look like this:
> 
> ```js
> /**
>  * @summary base pluralization
>  * @param {number} amount
>  * @returns {string}
>  */
> const pluralize = (amount, pluralSuffix = "s", singularSuffix = "") => amount !== 1 ? pluralSuffix : singularSuffix;
> ```
> 
> A less naive implementation could take into account different word forms English has in terms of pluralization

OK. I will try to implement that later. Thank you. :)

**Comment by kevinmmansour** [comment]
@double-beep Thank you for reporting. I understood now and I will try to solve in future versions.

**Comment by kevinmmansour** [comment]
Solved and deployed. Thank you. :)
